version: '3.5'

services:
  front:
    restart: unless-stopped
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: parser-front
    image: parser-front
    volumes:
      - ./front/:/app/
    networks:
      - parser
    env_file: .env

  api:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: parser-api
    image: parser-api
    networks:
      - parser
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    restart: unless-stopped
    container_name: parser-mongodb
    volumes:
      - ./data/mongodb:/data/db
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
    networks:
      - parser

  nginx:
    image: nginx:1.17
    container_name: parser-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 65005:80
    depends_on:
      - front
    networks:
      - parser

networks:
  parser:
    name: parser-network
    driver: bridge