version: '3.5'

services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    container_name: beard-mongodb
    env_file: .dev.env
    ports:
      - 127.0.0.1:$MONGO_PORT:27017
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
